[2017-05-12 15:55:33.354] [ERROR] [default] - user:[aa] SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'catch.corporations' doesn't exist
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-05-12 15:57:46.908] [ERROR] [default] - user:[aa] SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'catch.corporations' doesn't exist
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-05-12 15:57:47.786] [ERROR] [default] - user:[aa] SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'catch.corporations' doesn't exist
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-05-12 16:13:14.535] [ERROR] [default] - user:[aa] SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'catch.corporations' doesn't exist
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-05-12 16:13:14.539] [ERROR] console - Error: Failed to lookup view "error" in views directory "E:\NodejsWorkspace\catch\views"
    at EventEmitter.render (E:\NodejsWorkspace\catch\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (E:\NodejsWorkspace\catch\node_modules\express\lib\response.js:966:7)
    at E:\NodejsWorkspace\catch\app.js:79:7
    at Layer.handle_error (E:\NodejsWorkspace\catch\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:315:13)
    at E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:335:12)
    at next (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (E:\NodejsWorkspace\catch\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:315:13)
    at E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:335:12)
    at next (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:275:10)
    at E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:635:15
    at IncomingMessage.next (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:260:14)
    at done (E:\NodejsWorkspace\catch\node_modules\express\lib\response.js:961:25)
[2017-05-12 16:14:03.186] [ERROR] [default] - user:[aa] SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'catch.corporations' doesn't exist
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-05-12 16:14:03.197] [ERROR] console - Error: Failed to lookup view "error" in views directory "E:\NodejsWorkspace\catch\views"
    at EventEmitter.render (E:\NodejsWorkspace\catch\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (E:\NodejsWorkspace\catch\node_modules\express\lib\response.js:966:7)
    at E:\NodejsWorkspace\catch\app.js:81:7
    at Layer.handle_error (E:\NodejsWorkspace\catch\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:315:13)
    at E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:335:12)
    at next (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:275:10)
    at E:\NodejsWorkspace\catch\app.js:70:3
    at Layer.handle [as handle_request] (E:\NodejsWorkspace\catch\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:317:13)
    at E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:335:12)
    at next (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:275:10)
    at E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:635:15
    at next (E:\NodejsWorkspace\catch\node_modules\express\lib\router\index.js:260:14)
[2017-05-12 16:17:10.364] [ERROR] [default] - user:[aa] SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'catch.corporations' doesn't exist
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-05-12 16:17:42.535] [ERROR] [default] - user:[aa] SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'catch.corporations' doesn't exist
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-05-17 09:54:19.679] [ERROR] [default] - user:[aa] SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'customer' in 'field list'
    at Query.formatError (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (E:\NodejsWorkspace\catch\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (E:\NodejsWorkspace\catch\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\NodejsWorkspace\catch\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[2017-05-17 10:03:22.509] [ERROR] [default] - user:[aa] coupon.html initialize
[2017-05-17 14:26:45.298] [ERROR] [default] - user:[bb] coupon.html initialize
[2017-05-18 16:51:41.343] [ERROR] console - Error: E:\NodejsWorkspace\catch\views\error.hbs: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\NodejsWorkspace\catch\node_modules\express\lib\response.js:725:10)
    at ServerResponse.send (E:\NodejsWorkspace\catch\node_modules\express\lib\response.js:170:12)
    at done (E:\NodejsWorkspace\catch\node_modules\express\lib\response.js:962:10)
    at E:\NodejsWorkspace\catch\node_modules\hbs\lib\hbs.js:93:9
    at done (E:\NodejsWorkspace\catch\node_modules\hbs\lib\async.js:74:20)
    at E:\NodejsWorkspace\catch\node_modules\hbs\lib\hbs.js:88:18
    at E:\NodejsWorkspace\catch\node_modules\hbs\lib\hbs.js:69:11
    at done (E:\NodejsWorkspace\catch\node_modules\hbs\lib\async.js:74:20)
    at E:\NodejsWorkspace\catch\node_modules\hbs\lib\hbs.js:64:20
    at tryToString (fs.js:456:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
[2017-05-18 17:02:38.010] [ERROR] console - Error: E:\NodejsWorkspace\catch\views\error.hbs: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\NodejsWorkspace\catch\node_modules\express\lib\response.js:725:10)
    at ServerResponse.send (E:\NodejsWorkspace\catch\node_modules\express\lib\response.js:170:12)
    at done (E:\NodejsWorkspace\catch\node_modules\express\lib\response.js:962:10)
    at E:\NodejsWorkspace\catch\node_modules\hbs\lib\hbs.js:93:9
    at done (E:\NodejsWorkspace\catch\node_modules\hbs\lib\async.js:74:20)
    at E:\NodejsWorkspace\catch\node_modules\hbs\lib\hbs.js:88:18
    at E:\NodejsWorkspace\catch\node_modules\hbs\lib\hbs.js:69:11
    at done (E:\NodejsWorkspace\catch\node_modules\hbs\lib\async.js:74:20)
    at E:\NodejsWorkspace\catch\node_modules\hbs\lib\hbs.js:64:20
    at tryToString (fs.js:456:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
[2017-05-19 14:26:23.686] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-19 14:26:24.654] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-19 14:26:25.597] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-19 14:38:23.758] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-19 14:38:26.336] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-19 14:38:26.635] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-19 14:38:26.884] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-19 14:38:26.947] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-22 13:02:31.752] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-22 13:17:23.947] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-22 13:17:26.916] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-22 13:17:26.930] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-22 13:17:27.548] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-22 13:17:27.735] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-22 13:34:22.913] [ERROR] [default] - TypeError: Cannot read property 'destroy' of undefined
    at SequelizeStore.clearExpiredSessions (E:\NodejsWorkspace\catch\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:144:29)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-05-22 15:26:54.540] [ERROR] [default] - user:[bb] coupon.html initialize
[2017-05-22 16:42:38.535] [ERROR] [default] - user:[aa] coupon.html initialize
